name: Format and Create Release on Push

on:
  push:
    branches:
      - main

jobs:
  format_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x' # Use a compatible Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npm run format

      - name: Get Latest Tag
        id: get_latest_tag
        run: |
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          if [[ -z "$LATEST_TAG" ]]; then
            LATEST_TAG="v0.0.0"
          fi
          echo $LATEST_TAG
          echo ::set-output name=new_tag::$LATEST_TAG
        shell: bash

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.release_version || steps.get_latest_tag.outputs.new_tag }}
          release_name: Release ${{ github.event.inputs.release_version || steps.get_latest_tag.outputs.new_tag }}
          body: Auto-generated release for ${{ github.event.inputs.release_version || steps.get_latest_tag.outputs.new_tag }}
          draft: false
          prerelease: false
