name: Format and Create Release on Push

on:
  push:
    branches:
      - main

jobs:
  format_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npm run format

      - name: Get Latest Tag
        uses: actions/github-script@v5
        with:
          script: |
            const response = await github.repos.listTags({
              ...context.repo,
              per_page: 1,
              order: 'desc'
            });
            const latestTag = response.data[0]?.name || 'v0.0.0';
            const version = latestTag.replace(/^v/, '').split('.').map(Number);
            version[2]++;
            const newTag = `v${version.join('.')}`;
            console.log(newTag);
            core.setOutput('new_tag', newTag);

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_latest_tag.outputs.new_tag }}
          release_name: Release ${{ steps.get_latest_tag.outputs.new_tag }}
          body: Auto-generated release for ${{ steps.get_latest_tag.outputs.new_tag }}
          draft: false
          prerelease: false
